### ISSUE TITLE
wooga/eredis or Nordix/eredis?

### ISSUE THREAD

**Issue by zuiderkwast** [HalloAppInc/ecredis#49]
README says Nordix/eredis, but rebar.config says `{git, "https://github.com/wooga/eredis.git", {tag, "v1.0.8"}}`, which is quite old.

Btw, nice project! I had this idea of skipping the connection pools (in eredis_cluster) and just use one eredis per node, but I didn't try it yet.

Some more thoughts:

* There's no way to supply options to eredis. (Options may include TLS certs, AUTH username and password and some other ones.)
* How do you do WATCH-get-MULTI-set-EXEC? You can call `q()` multiple times and get the same eredis connection, but what if you get a redirect in the middle and the mapping is reloaded? (It's also possible that the eredis client reconnects automatically, which is also a potential problem in eredis_cluster. We could do something in eredis about this if we need.)

**Comment by NikolaBorisov** [comment]
I will try to switch to Nordix

Filed this issue:
https://github.com/HalloAppInc/ecredis/issues/52

Yes we need to work on the WATCH-get-MULTI-set-EXEC. We have not had this case come up so far.

**Comment by zuiderkwast** [comment]
Ah, nice. I saw the issue for rebar2.

I misread your README. It mentions Nordix/eredis_cluster, not Nordix/eredis.

**Comment by NikolaBorisov** [comment]
Closing this. We switched ecredis to Nordix/eredis now
